nextcloud:
  trustedDomains:
    - 'nextcloud.nextcloud.svc.cluster.local'
    - 'nextcloud.iscc-system.org'
  fullname: nextcloud-dev
  host: nextcloud.iscc-system.org
  username: admin
  password: isccpassword
#  extraEnv:
#    - name: REDIS_HOST
#      value: redis-master.isccdb-dev.svc.cluster.local
#    - name: REDIS_HOST_PORT
#      value: "6379"
#    - name: REDIS_PASSWORD
#      value: myRootPassword

redis:
  auth:
    password: myRootPassword

replicaCount: 2

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  host: mariadb.isccdb-dev.svc.cluster.local
  database: isccnextclouddb
  user: isccmysqladmin
  password: isccpassword

startupProbe:
  enabled: true

livenessProbe:
  initialDelaySeconds: 120

readinessProbe:
  initialDelaySeconds: 120

persistence:
  enabled: true
  size: 200Gi

ingress:
  enabled: true
  className: external
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    forecastle.stakater.com/appName: NextCloud
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: ISCC Services
    forecastle.stakater.com/icon: https://raw.githubusercontent.com/hashicorp/vault/refs/heads/main/ui/public/vault-logo.svg
  tls:
    - hosts:
        - nextcloud.iscc-system.org
      secretName: nextcloud-tls

redis:
  enabled: true
  auth:
    password: myRootPassword