apiVersion: batch/v1
kind: Job
metadata:
  name: create-database
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
  namespace: nextcloud-dev
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-mysql
          image: mariadb:10.11
          command:
            - /bin/sh
            - -c
            - |
              until mysql -h $MYSQL_HOST \
                -uroot -p"$MYSQL_ROOT_PASSWORD" \
                -e "USE $MYSQL_DEFAULT_DATABASE"; do
                echo "Waiting for database to be ready..."
                sleep 3
              done
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: preinstall-secret
                  key: MYSQL_HOST
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: preinstall-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DEFAULT_DATABASE
              valueFrom:
                secretKeyRef:
                  name: preinstall-secret
                  key: MYSQL_DEFAULT_DATABASE
      containers:
        - name: create-db
          image: mariadb:10.11
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: preinstall-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: preinstall-secret
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: preinstall-secret
                  key: NEXTCLOUD_MYSQL_USER
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: preinstall-secret
                  key: NEXTCLOUD_MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: preinstall-secret
                  key: NEXTCLOUD_MYSQL_PASSWORD
          command: ["sh", "-c"]
          args:
            - |
              mysql -h $MYSQL_HOST -uroot -p$MYSQL_ROOT_PASSWORD -e "
              CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\`;
              CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
              GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE\`.* TO '$MYSQL_USER'@'%';
              FLUSH PRIVILEGES;"
      restartPolicy: Never
  backoffLimit: 3