apiVersion: v1
kind: Secret
metadata:
  name: preinstall-secret
  namespace: nextcloud-dev
type: Opaque
data:
  NEXTCLOUD_MYSQL_PASSWORD: aXNjY3Bhc3N3b3Jk # isccpassword
  NEXTCLOUD_MYSQL_DATABASE: aXNjY25leHRjbG91ZGRi # isccnextclouddb
  NEXTCLOUD_MYSQL_USER: aXNjY215c3FsYWRtaW4= # isccmysqladmin
  MYSQL_HOST: bWFyaWFkYi5pc2NjZGItZGV2LnN2Yy5jbHVzdGVyLmxvY2FsCg== # mariadb.isccdb-dev.svc.cluster.local
  MYSQL_ROOT_PASSWORD: bXlSb290UGFzc3dvcmQK # myRootPassword
  MYSQL_DEFAULT_DATABASE: bXlEYXRhYmFzZQo= # myDatabase
  REDIS_PASSWORD: bXlSb290UGFzc3dvcmQK # myRootPassword