architecture: "replication"

auth:
  rootPassword: myRootPassword
  database: myDatabase
  replicationPassword: "newReplicationPassword123"

replication:
  enabled: true
  replicaCount: 2


primary:
  resources:
    requests:
      cpu: "1"
      memory: "1000Mi"
    limits:
      cpu: "1"
      memory: "1000Mi"
  persistence:
    size: 12Gi

secondary:
  replicaCount: 2
  resources:
    requests:
      cpu: "1"
      memory: "1000Mi"
    limits:
      cpu: "1"
      memory: "1000Mi"
  persistence:
    size: 11Gi

networkPolicy:
  ingressNSMatchLabels:
    environment: "development"