auth:
  rootPassword: myRootPassword
  database: myDatabase

replication:
  enabled: true
  replicaCount: 2


primary:
  persistence:
    size: 12Gi

secondary:
  replicaCount: 2
  persistence:
    size: 11Gi

networkPolicy:
  ingressNSMatchLabels:
    environment: "development"